/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quartointeligente;

import java.util.Scanner;

/**
 *
 * @author Luís Fernando
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        boolean existir=false;
        boolean Porta=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaDados = new javax.swing.JTextArea();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        SaidaDados = new javax.swing.JTextPane();
        Entrar = new javax.swing.JToggleButton();
        Sair = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Interface Jarvis");

        EntradaDados.setColumns(20);
        EntradaDados.setRows(5);
        EntradaDados.setText("Digite aqui:");
        jScrollPane1.setViewportView(EntradaDados);

        jScrollPane2.setViewportView(SaidaDados);

        Entrar.setText("Entrar");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });

        Sair.setText("Sair");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(10, 10, 10)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel1)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Entrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sair)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Entrar)
                    .addComponent(Sair))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
        boolean Porta=true;
        boolean Luz=true;
        boolean Janela=false;
        boolean Ventilador=false;
        String VeloVentilador="5";
        jLabel1.setText("Qual o seu nome?");
        String Nome=EntradaDados.getText();
         jLabel1.setText("");
         jLabel1.setText("Olá"+Nome+"Bem vindo ao seu quarto virtual");
         jLabel1.setText("Me chamo Jarvis e vou lhe guiar nele. Seu quarto está: ");
        if (Porta){
            SaidaDados.setText("A porta esta aberta");
        }
        else{
            SaidaDados.setText("A porta esta fechada");
        }
        if (Janela){
            SaidaDados.setText("A janela esta aberta");
        }
        else{
            SaidaDados.setText("A janela esta fechada");
        }
        if (Ventilador){
            SaidaDados.setText("O ventilador está ligado com velocidade: "+VeloVentilador);
        }
        else{
            SaidaDados.setText("O ventilador está desligado");
        }
        if(Luz){
            SaidaDados.setText("A luz está ligada");
        }
        else{
            SaidaDados.setText("A luz está desligada");
        }
        
        boolean k=false;
        String y;
         System.out.println("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
        while (k==false){
            SaidaDados.setText("\n");
            SaidaDados.setText("Bem vindo ao menu, selecione a opção desejada: ");
            SaidaDados.setText("1- Abrir/fechar com a porta");
            SaidaDados.setText("2- Abrir/fechar com a janela");
            SaidaDados.setText("3- Ligar/desligar com a luz");
            SaidaDados.setText("4- Ligar/desligar com o ventilador");
            SaidaDados.setText("5- Mudar a velocidade do ventilador");
            SaidaDados.setText("6- Verificar a situação do quarto");
            SaidaDados.setText("7- Sair");
            y=EntradaDados.getText();
            if (null == y){
                SaidaDados.setText("Opção inválida");
            }
            else switch (y) {
                case "1":
                    if (Porta){
                        Porta=false;
                    }
                    else{
                        Porta=true;
                    }   break;
                case "2":
                    if (Janela){
                        Janela=false;
                    }
                    else{
                        Janela=true;
                    }   break;
                case "3":
                    if (Luz){
                        Luz=false;
                    }
                    else{
                        Luz=true;
                    }   break;
                case "4":
                    if (Ventilador){
                        Ventilador=false;
                    }
                    else{
                        Ventilador=true;
                    }   break;
                case "5":
                    String x="0";
                    boolean chave=false;
                    if (Ventilador){
                        while (chave==false){
                            SaidaDados.setText("Por favor "+Nome+ " Coloque a velocidade do ventilador de 1 a 10");
                            x=EntradaDados.getText();
                            if ( !"1".equals(x) || !"2".equals(x) || !"3".equals(x)|| !"4".equals(x)|| !"5".equals(x)|| !"6".equals(x)|| !"7".equals(x)|| !"8".equals(x)|| !"9".equals(x)|| !"10".equals(x)){
                                SaidaDados.setText("Calma lá amigão ta errado");
                            }
                            else{
                                VeloVentilador=x;
                                chave=true;
                            }
                        }
                        if (null != VeloVentilador)switch (VeloVentilador) {
                    case "1":
                    case "2":
                    case "3":
                        SaidaDados.setText("shhhhhhhhhhhh");
                        break;
                    case "4":
                    case "5":
                    case "6":
                        SaidaDados.setText("wooooooooooooooooo");
                        break;
                    case "7":
                    case "8":
                    case "9":
                    case "10":
                        SaidaDados.setText("PA-PA-PA-PA-PA-PA");
                        break;
                    default:
                        break;
                }
                    }
                    else
                    {
                        SaidaDados.setText("O ventilador está desligado, não é possivel mudar sua velocidade.");
                    }   break;
                case "6":
                    SaidaDados.setText("");
                    SaidaDados.setText("Olá "+Nome+" Bem vindo ao seu quarto virtual");
                    SaidaDados.setText("Me chamo Jarvis e vou lhe guiar nele. Seu quarto está: ");
                    if (Porta){
                        SaidaDados.setText("A porta esta aberta");
                    }
                    else{
                        SaidaDados.setText("A porta esta fechada");
                    }   if (Janela){
                        SaidaDados.setText("A janela esta aberta");
                    }
                    else{
                        SaidaDados.setText("A janela esta fechada"); 
                    }   if (Ventilador){
                        SaidaDados.setText("O ventilador está ligado com velocidade: "+VeloVentilador);
                    }
                    else{
                        SaidaDados.setText("O ventilador está desligado");
                    }   if(Luz){
                        SaidaDados.setText("A luz está ligada");
                    }
                    else{
                        SaidaDados.setText("A luz está desligada");
                    }   break;
                case "7":
                    if (Porta){
                        k=true;
                    }   if(Porta){
                        SaidaDados.setText("Tchau "+Nome+" desligarei e fecharei tudo para você");
                        Janela=false;
                        Luz=false;
                        Porta=false;
                        Ventilador=false;
                    }
                    else if(Janela){
                        SaidaDados.setText("Quer pular a janela é ? a Porta ta fechada, abra-a para sair");
                    }
                    else{
                        SaidaDados.setText("A porta está fechada, abra-a para sair");
                    }   break;
                default:
                    SaidaDados.setText("Opção inválida");
                    break;
            }
        }
    }//GEN-LAST:event_EntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea EntradaDados;
    private javax.swing.JToggleButton Entrar;
    private javax.swing.JTextPane SaidaDados;
    private javax.swing.JToggleButton Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
